#!/usr/bin/env bash
# Step 80 — persistent post-provision follow-ups. The manual follow-ups (git
# identity, `nvm install --lts`, Docker mode choice, …) otherwise print to
# stdout ONCE at the end of a run — and a GOLDEN build never prints them at all
# (it exits + wipes before the summary), so a clone / cloud-init user would
# have no on-box record. This step writes them to ~/PROVISION-NEXT-STEPS.md and
# adds an MOTD pointer; the text itself is lib.sh's next_steps_text() — one
# source of truth shared with provision.sh's end-of-run print.
#
# Survives the golden wipe BY CONSTRUCTION: finalize (step 90) never touches
# /etc/update-motd.d, and in $HOME it removes only creds/keys/history (its
# leftover-warn scan flags repos and *.log — a .md is neither).
#
# The MOTD drop-in is SELF-SILENCING: it prints only while the .md still
# exists, so "delete the file when done" is the entire cleanup.
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/../lib.sh"

NOTES_FILE="$TARGET_HOME/PROVISION-NEXT-STEPS.md"
MOTD_FILE=/etc/update-motd.d/99-provision-next-steps

log "Post-provision notes: $NOTES_FILE + MOTD pointer"

if dry; then
  would "write $NOTES_FILE (the manual follow-ups, owned by $TARGET_USER)"
  would "write $MOTD_FILE (0755 login notice; silent once the .md is deleted)"
  exit 0
fi

# The notes file. Re-running overwrites it — intentional: a re-provision (e.g.
# bring-to-latest on a golden) means the follow-ups are worth re-checking.
# rm FIRST (rm doesn't follow symlinks): we write as root into a user-owned
# home, so a pre-placed symlink at this path must not redirect the write/chown
# to an arbitrary file (multi-user-box hardening).
write_notes() {
  $SUDO rm -f "$NOTES_FILE"
  {
    printf '# Post-provision follow-ups\n\n'
    printf 'Generated by dotfiles provision.sh on %s for user %s.\n' \
      "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$TARGET_USER"
    printf 'Delete this file once done — the login (MOTD) notice disappears with it.\n\n'
    next_steps_text
  } | $SUDO tee "$NOTES_FILE" >/dev/null \
    && $SUDO chown "$TARGET_USER":"$TARGET_GROUP" "$NOTES_FILE"
}
write_notes || soft_fail "could not write $NOTES_FILE"

# MOTD drop-in: a one-line pointer, not the full text (pam_motd runs these as
# root at every login — keep it quiet and cheap). Unquoted heredoc on purpose:
# $NOTES_FILE/$MOTD_FILE are baked in at write time. Must be executable (0755)
# or pam_motd silently skips it.
write_motd() {
  $SUDO tee "$MOTD_FILE" >/dev/null <<EOF && $SUDO chmod 0755 "$MOTD_FILE"
#!/bin/sh
# Added by dotfiles provisioning — pointer to the post-provision follow-ups.
# Self-silencing: prints nothing once the notes file is gone. To drop the
# pointer itself:  sudo rm $MOTD_FILE
[ -f "$NOTES_FILE" ] || exit 0
echo ""
echo ">>> Provisioning follow-ups pending — see $NOTES_FILE"
EOF
}
write_motd || soft_fail "could not install MOTD drop-in $MOTD_FILE"
